const express=require("express")
const upload=require("../../utiles/multer_providetr")
const WebIndexRouter=express.Router()
const IndexController=require("../../controller/website/IndexController")
// const WebIndexRouter= require("../../app")
const authMiddlware=require("../../middleware/auth")

//WebIndexRouter.get("/",IndexController.getdemo)
WebIndexRouter.get("/",IndexController.getWebIndex)

WebIndexRouter.get("/getSubCategoryShow",IndexController.getSubCategoryShow)
WebIndexRouter.get("/getChildCategoryBySubCategory",IndexController.getChildCategoryBySubCategory)
WebIndexRouter.get("/showAllCategory",IndexController.showAllCategory)
WebIndexRouter.get("/showSubCategoryById",IndexController.showSubCategoryById)
WebIndexRouter.get("/showChildById",IndexController.showChildById)
WebIndexRouter.get("/showProductById",IndexController.showProductById)
WebIndexRouter.get("/showAllCategoryNew",IndexController.showAllCategoryNew)
WebIndexRouter.get("/showAllProduct",IndexController.showAllProduct)
WebIndexRouter.get("/getBlogById",IndexController.getBlogById)
WebIndexRouter.get("/detailOfBlog",IndexController.detailOfBlog)
WebIndexRouter.get("/getSlugPage",IndexController.getSlugPage)
WebIndexRouter.get("/getContactPage",IndexController.getContactPage)
WebIndexRouter.post("/contactSubmit",IndexController.contactSubmit)
WebIndexRouter.post("/searchBlog",IndexController.searchBlog)
WebIndexRouter.get("/paggination",IndexController.paggination)
WebIndexRouter.post("/getLike",IndexController.getLike)
WebIndexRouter.post("/getUnLike",IndexController.getUnLike)
WebIndexRouter.post("/getComments",IndexController.getComments)
WebIndexRouter.get("/showComments",IndexController.showComments)
WebIndexRouter.get("/deleteComment",IndexController.deleteComment)

module.exports=WebIndexRouter